version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: test
      # You should definitely change the password in production
      POSTGRES_PASSWORD: main
      POSTGRES_USER: main

